### ISSUE TITLE
Add Hystrix Middleware

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#100]
I'd like to have basic hystrix out of the box that works for 80+% of our use cases. I'd propose to use:
- [ ] url pattern = command key
- [ ] client id (configurable upon creation) = command group + thread pool key

see https://github.com/Netflix/Hystrix/wiki/How-To-Use#CommandName

**Comment by lukasniemeier-zalando** [comment]
Do we want to move this issue to a different milestone?

**Comment by whiskeysierra** [comment]
Just as a reference how feign produces group and command keys: https://github.com/OpenFeign/feign/tree/master/hystrix#group-and-command-keys
