### ISSUE TITLE
Support streaming processing of responses

### ISSUE THREAD

**Issue by jhorstmann** [zalando/riptide#101]
Not sure how well this would fit in with riptide and resttemplate, but it would be nice to have riptide support streaming of for example newline delimited json, as used in nakadi or the twitter api

**Comment by whiskeysierra** [comment]
Can we do this while still relying on Spring's *abstraction*, i.e. the `ClientHttpRequest/Factory`?

**Comment by whiskeysierra** [comment]
Just based on the API it should be possible:

```java
public interface ClientHttpResponse extends HttpInputMessage, Closeable {
    ..
}

public interface HttpInputMessage extends HttpMessage {

	/**
	 * Return the body of the message as an input stream.
	 * @return the input stream body (never {@code null})
	 * @throws IOException in case of I/O Errors
	 */
	InputStream getBody() throws IOException;

}
```

**Comment by whiskeysierra** [comment]
I'd suggest to externalize this into its own module: `riptide-stream`
