### ISSUE TITLE
[Question] Is it possible to config Riptide not to use its own thread pool?

### ISSUE THREAD

**Issue by jadetang** [zalando/riptide#1017]
Hi, is it possible to config Riptide not to use its own thread pool?
Basically, in the code, we are doing everything synchronously. So we do not benefit from using the thread pool.

**Comment by whiskeysierra** [comment]
Sure, just use `Runnable::run` as your executor:

```java
Http.builder()
    .executor(Runnable::run)
    .requestFactory(new HttpComponentsClientHttpRequestFactory(client))
    // ....
    .build();
```

**Comment by whiskeysierra** [comment]
Actually, that's the default, so you can just drop it:

```java
Http.builder()
    .requestFactory(..)
   // ...
    .build();
```

**Comment by jadetang** [comment]
Is it possible to config this in YAML?

**Comment by whiskeysierra** [comment]
Sure, see https://github.com/zalando/riptide/tree/main/riptide-spring-boot-autoconfigure#reference.

```yaml
riptide:
  clients:
    example:
      threads.enabled: false
```

**Comment by jadetang** [comment]
that's amazing, thanks.
