### ISSUE TITLE
Why always buffer the response?

### ISSUE THREAD

**Issue by jhorstmann** [zalando/riptide#102]
In https://github.com/zalando/riptide/blob/master/src/main/java/org/zalando/riptide/Rest.java#L74 the response is always buffered. If I understand the history correctly this should only be needed in the `OAuth2CompatibilityResponseErrorHandler`.

When I replace the extractor `BufferingClientHttpResponse::buffer` with just `r -> r` all tests are still passing, so if this behaviour is really needed there should be a test documenting why it's needed.

**Comment by whiskeysierra** [comment]
> When I replace the extractor BufferingClientHttpResponse::buffer with just r -> r all tests are still passing

Are we using a ByteArrayInputStream?

**Comment by jhorstmann** [comment]
> Are we using a ByteArrayInputStream

Probably, but it's still an InputStream that can only be read once. The way I understand it, buffering is only needed for oauth errors and even there it [looks like our error handler would get an already buffered response][1].

 [1]: https://github.com/spring-projects/spring-security-oauth/blob/master/spring-security-oauth2/src/main/java/org/springframework/security/oauth2/client/http/OAuth2ErrorHandler.java#L151

**Comment by whiskeysierra** [comment]
I can't remember why we did it. @lukasniemeier-zalando Do you?

**Comment by lukasniemeier-zalando** [comment]
I also don't remember why, my guess would have been to protect against error handlers (like OAuth). Or does the `RestTemplate` itself close the stream in `execute`?

**Comment by jhorstmann** [comment]
Fixed by PR #104
