### ISSUE TITLE
Verify that capturing lists works

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#103]
```java
rest.get("/api").dispatch(series(),
        on(SUCCESSFUL).capture(Body.class, this::map))
        .to(listOf(String.class));

private List<String> map(final Body body) {
    // ...
}
```

**Comment by whiskeysierra** [comment]
Assuming that we're going to discourage the use of arrays as top-level structures in responses (see zalando/restful-api-guidelines/63) maybe it makes sense that Riptide has to first-class citizen support for this. Nevertheless, it should still be possible without too much hassle (e.g. without unsafe casts).

**Comment by lukasniemeier-zalando** [comment]
I'd go with having the user explicitly specifying the input and output types of the mapping function

```java
rest.get("/api").dispatch(series(),
        on(SUCCESSFUL).capture(Body.class, listOf(String.class), this::map))
        .to(listOf(String.class));
```

**Comment by whiskeysierra** [comment]
First things first, I agree. **But** I tried this on a local branch and it's horrible, it's just :hankey:. When we require it for everyone, regardless of types (generic or not) we're basically punishing everyone equally for Java's shortcomings in terms of type erasure. That feels just wrong. Using Riptide's unique syntax was meant to be fun, this just is no fun, no fun at all :rage:. But enough with the rant, I'd propose to go for the following principles:

1. Make it easy and fun to use in 95%+ of all use cases...
2. but still support the remaining 5%, with a slightly less-fun API, if needed
3. Make it as hard to shoot yourself in the foot as possible

I'd propose the following changes:

1. Every version of `capture` and `call` will be overloaded to have a version without any type information and once with full type information (two overloaded versions, once with Class and once with TypeToken)
2. The ones with type information behave as expected and look like in the previous example
3. The overloaded versions without type information use type inference
  1. We use https://github.com/jhalterman/typetools on the given lambda during *declaration* time
  2. If it fails we throw an exception early (at declaration time, not when we actually dispatch)

Thoughts?

**Comment by lukasniemeier-zalando** [comment]
But isn't _typetools_ relying on type information of a concrete subtype? And those mapping-functions are just generic `EntityFunction`s right now. What do I miss?

**Comment by whiskeysierra** [comment]
But they *are* actual subtypes of `EntityFunction`. It basically allows to do this:

```java
on(200).capture((String body) -> new Name(body))
```

Automatically uses `String.class` as a type hint for the message conversion and `Name.class` as the type hint for the Capture instance.

**Comment by lukasniemeier-zalando** [comment]
Sure, but this is already working without _typetools_ if I am not mistaken. I don't see where _typetools_ should get the information from in helping with the generics (capturing lists of xyz).

**Comment by whiskeysierra** [comment]
> Sure, but this is already working without typetools if I am not mistaken.

Kind of. It only works because we basically use `getClass()` on the object returned by the function. With typetools we could get that information a bit earlier (when constructing the statement vs. when actually dispatching a response). It won't help with listOf, but it would allow to drop the type hint parameters altogether most of the time. When we can verify the generic function types early we could check if it's a generic type and fail fast at that point already. That should minimize the potential to shoot yourself in the foot.

**Comment by jhorstmann** [comment]
The tricky thing that library seems to solve are lambdas / method references. For actual or anonymous implementations of `EntityFunction` we could just add a hack like the following in `Conditions` before creating the `Capture` instances:

    @SuppressWarnings("unchecked")
    private <I, T> TypeToken<T> getTargetType(EntityFunction<I, T> function) {
        TypeToken<?> typeToken = Arrays.stream(function.getClass().getGenericInterfaces())
                .filter(ParameterizedType.class::isInstance)
                .map(ParameterizedType.class::cast)
                .filter(type -> type.getRawType() == EntityFunction.class)
                .findFirst()
                .map(type -> TypeToken.of(type.getActualTypeArguments()[1]))
                .get();
        return (TypeToken<T>) typeToken;
    }

**Comment by jhorstmann** [comment]
How ever, capturing lists themselves works, the problem exists only in combinaton with mapping functions. We could just throw an exception in that case to notify users that this usecase is not currently supported.

**Comment by whiskeysierra** [comment]
> We could just throw an exception in that case to notify users that this usecase is not currently supported.

We could actually support it, but we need both types (input and output) in addition to the function:

```java
capture(listOf(Foo.class), listOf(Bar.class), (List<Foo> foos) -> ..);
```

But that is sooo ugly. Feels like ancient Java where one needed to specify generic types for variables and constructors again. Did I mention that it's ugly? It's sooo ugly...

**Comment by whiskeysierra** [comment]
> For actual or anonymous implementations of EntityFunction

That probably only 1% of users will ever do, now that we have lambdas and method references.

**Comment by jhorstmann** [comment]
I have something that works for method references and implementations of the interface. Strangely does not work for lambdas, I'm still trying to find out why the compiler does not embed the generic signature in that case. I also don't know yet how to distinguish lambdas and method references so we could throw an exception.
