### ISSUE TITLE
[Docs] Riptide 3 Spring Boot version requirement misinformation

### ISSUE THREAD

**Issue by yuppie-flu** [zalando/riptide#1057]
## Description
Riptide 3 [migration guide](https://github.com/zalando/riptide/blob/main/MIGRATION.md) mentions:
> The Starter and Auto Configuration require Spring Boot 2.0 though.

However in fact they require at least Spring Boot 2.2, because of `Binder.bindOrCreate` method usage [here](https://github.com/zalando/riptide/blob/628f979d0419fb33ba534fa20d255dcf2dd712a1/riptide-spring-boot-autoconfigure/src/main/java/org/zalando/riptide/autoconfigure/RiptidePostProcessor.java#L34).
This method was added only in 2.2.0 - see [javadoc](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/context/properties/bind/Binder.html#bindOrCreate-java.lang.String-java.lang.Class-) for example.

**Comment by fatroom** [comment]
Thank you for pointing out. Documentation is updated to reflect correct requirements.
