### ISSUE TITLE
Check for consistent exception handling

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#107]
- [ ] Are we catching/rethrowing/wrapping exceptions somewhere?
- [ ] If yes, should we?
- [ ] Define clear rules + tests for exception handling inside riptide itself
- [ ] Document it

**Comment by jhorstmann** [comment]
My suggestion would be to replace the `SneakyThrows` and `throws Exception` in `ThrowingFunction` / `ThrowingConsumer` with more specific `IOException` where needed.

The changes don't seem to be that big: https://github.com/zalando/riptide/compare/feature/unified-syntax...jhorstmann:feature/unified-syntax-exception-handling?expand=1

**Comment by whiskeysierra** [comment]
My idea would be to allow clients to throw *any* exception, not just `IOException` as that would be very limiting.

**Comment by jhorstmann** [comment]
That would also mean bubbling exceptions up to the outermost level and then forcing the client to handle everything. With `SneakyThrows` the behaviour is similar, but the client might not even be aware he has to handle exceptions. I'd much prefer to have IOExceptions explicit, because they can be thrown by `ResponseExtractor` and nearly all method on `ClientHttpResponse`, and have the user wrap everything else in either `IOException` or unchecked exceptions himself.

**Comment by whiskeysierra** [comment]
To summarize:

- no `@SneakyThrows`
- dispatch(..): throws IOException
- Throwing* throws IOException
- better name for Throwing* callbacks? IOConsumer? IOFunction?

**Comment by whiskeysierra** [comment]
@jhorstmann @lukasniemeier-zalando 

While introducing AsyncRest as the (one and only) default I realized we implicitly introduce up to three additional exception users have to handle. Together with the known ones this leads to:

- IOException (HttpClient, Callbacks, ...)
- NoRouteException (Riptide)
- ExecutionException (Future)
- InterruptedException (Future)
- TimeoutException (Future)

**Comment by jhorstmann** [comment]
> InterruptedException (Future)

Urgh, that's the exception that nearly no one is handling correctly

> ExecutionException (Future)

Can wrap any `Throwable` which makes this even uglier. But if our callbacks are only allowed to throw `IOException` or unchecked exception then those can be the only causes, so maybe it's possible to unwrap it.

**Comment by whiskeysierra** [comment]
> Urgh, that's the exception that nearly no one is handling correctly

Side note: [How to do it correctly](http://www.ibm.com/developerworks/library/j-jtp05236/), for everyone who is interested. Everything one needs to know about `InterruptedException`.

> But if our callbacks are only allowed to throw IOException or unchecked exception then those can be the only causes, so maybe it's possible to unwrap it.

It's always possible, but inconvenient for the users.

**Comment by lukasniemeier-zalando** [comment]
What Kind of IOExceptions would not be wrapped inside the ExecutionException? What is done outside of the future?

TimeoutException only for `get` with Timeout I assume.

**Comment by whiskeysierra** [comment]
The next problem is that the following features won't work anymore

```java
on(UNPROCESSABLE_ENTITY).call(ThrowableProblem.class, propagate()),
```

(If someone handles those exceptions correctly, it would work.)

```java
private String send(final URI url) throws ExecutionException, InterruptedException {
    return unit.post(url).dispatch(series(),
            on(SUCCESSFUL).capture(String.class),
            on(REDIRECTION).capture(location().andThen(this::send)))
            .get()
            .to(String.class);
}
```

**Comment by whiskeysierra** [comment]
> What Kind of IOExceptions would not be wrapped inside the ExecutionException?

See next point.

> What is done outside of the future?
Actually sending/preparing the request is done before and it will throw IOException directly.

> TimeoutException only for get with Timeout I assume.

Correct.
