### ISSUE TITLE
Add builder for Rest

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#112]
Required:
- ClientHttpRequestFactory

Optional:
- HttpMessageConverter (default none; in most cases you'll need one, but in theory we can do it without one, e.g. if someone only handles raw client responses)
- UriTemplateHandler (default: no base url)

**Comment by lukasniemeier-zalando** [comment]
to be done in #111 ?

**Comment by whiskeysierra** [comment]
Not necessarily.

**Comment by jhorstmann** [comment]
Let's keep this separate for now, with 3 parameters (of which 2 are nearly always required) a builder is not strictly necessary. Especially since you normally build one instance and then inject it everywhere.

**Comment by whiskeysierra** [comment]
```java
Rest.builder(new SimpleClientHttpRequestFactory())
    .converter(new MappingJackson2HttpMessageConverter())
    .converter(new StringHttpMessageConverter())
    .converter(new Jaxb2RootElementHttpMessageConverter())
    .baseUrl("https://service.team.example.com/api")
```

**Comment by lukasniemeier-zalando** [comment]
> HttpMessageConverter (default none)

Or use the `RestTemplate`'s default as you've said.

**Comment by whiskeysierra** [comment]
> Or use the RestTemplate's default as you've said.

Yes. Basically `new RestTemplate().getMessageConverters()`.
