### ISSUE TITLE
sliding window based circuit breaker config

### ISSUE THREAD

**Issue by jbspeakr** [zalando/riptide#1163]
Support sliding window based circuit breaker config. 

## Detailed Description

Failsafe allows to configure [sliding window based circuit breaker config](https://failsafe.dev/circuit-breaker/), which is what we actually need in most cases (compared to the ratio based configuration currently exposed).

```
A time based circuit breaker can be configured to open when a number of failures occur within a time period:

breaker.withFailureThreshold(3, Duration.ofMinutes(1));
```

## Context
[riptide-spring-boot-autoconfigure](https://github.com/zalando/riptide/tree/main/riptide-spring-boot-autoconfigure) currently seems to not support this time-based approach.

**Comment by fatroom** [comment]
Released with the version 3.2
