### ISSUE TITLE
Don't use Capture as a return value

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#117]
By returning Capture (or future thereof) we have the burden to preserve type safety. If the change this we can let the client handle this in a safer and easier way:

```java
Capture<List<String>> capture = Capture.empty();

http.get("/").dispatch(series(),
        on(SUCCESSFUL).call(capture),
        anySeries().call(fail))
        .get(10, SECONDS);

capture.retrieve(); // throws NotReadyException vs EmptyException
```

**Benefits**
- completely type safe
- no unsafe casts
- easy to understand for clients
- API is now 100% callbacks
- does not even need to be part of the core API (even though it probably will)

This will complete get rid of the problematic of #114.

- [x] externalize into own module: `riptide-capture`

**Comment by lukasniemeier-zalando** [comment]
If a client wants to expose the `Future`, how should they pass/retrieve a reference to the `Capture` in their application code?

**Comment by whiskeysierra** [comment]
I guess one way would be to create an adapter that combines Future<?> + Capture<T> to a Future<T>.

**Comment by whiskeysierra** [comment]
The factory method for that could be in Capture already:

```java
public Future<List<String>> remote() {
    Capture<List<String>> capture = Capture.empty();

    final Future<?> future = http.get("/).dispatch(series(),
            on(SUCCESSFUL).call(capture),
            anySeries().call(fail));

    return capture.adapt(future);
}
```

**Comment by tkrop** [comment]
I don't understand. If you already provide callbacks for success and fail, that will catch the result. What do we need to capture anything at all here? So why to bother about the future at all - it just repeats the result from capture/fail without the routing knowledge? Users should not even depend on this information.

**Comment by whiskeysierra** [comment]
There will be cases where clients want a synchronous response, in those cases a callback-style API is not very user friendly. This is the reason why we have capture in the first place. I see it as a usability extension to make synchronous return values easier.
