### ISSUE TITLE
Release 2.0.0-RC1

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando/riptide#121]
Before finalizing all the documentation tasks #106 #76 #110 we can already have a RC to test.

**Comment by whiskeysierra** [comment]
https://github.com/zalando/riptide/releases/tag/2.0.0-RC1

**Comment by lukasniemeier-zalando** [comment]
Will this also be released on [maven central](https://mvnrepository.com/artifact/org.zalando/riptide)?

**Comment by whiskeysierra** [comment]
http://search.maven.org/#search|ga|1|riptide
