### ISSUE TITLE
Add OAuth Example Usage to README

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando/riptide#123]
Now that we have dropped support for the `RestTemplate` we should add an example on how to do authorization (e.g. OAuth) with riptide 2.0

**Comment by whiskeysierra** [comment]
Especially with the Stups OAuth2 tooling?

**Comment by lukasniemeier-zalando** [comment]
### Authorization

You can add authorization headers by registering a `HttpRequestInterceptor` on the `clientRequestFactory` (sic?).

```java
public class AuthorizationRequestInterceptor implements HttpRequestInterceptor {
    @Override
    public void process(final HttpRequest request, final HttpContext context) throws Exception{
        request.setHeader("Authorization", "Authorization: Bearer SECRET");
    }
}
```

Check [here](https://github.com/zalando-stups/stups-spring-oauth2-support/blob/master/stups-http-components-oauth2/src/main/java/org/zalando/stups/oauth2/httpcomponents/AccessTokensRequestInterceptor.java) for an example using the STUPS OAuth tooling.

**Comment by whiskeysierra** [comment]
It doesn't really fit into the whole readme of riptide anymore, especially conceptually. I feel like we should have (optional) support for RestTemplate in Put it to REST.
