### ISSUE TITLE
Add a custom AsyncClientHttpRequestFactory that returns a streamable Future

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#131]
The futures returned by the request implementations of SimpleClientHttpRequestFactory and HttpComponentsAsyncClientHttpRequestFactory have different semantics:
1. Simple returns immediately after the headers are there
2. Apache returns only after the whole body is read

Since we need option 1 for streaming we should implement a custom version based on Apache that does it. My idea would be to use [PipedInputStream](https://docs.oracle.com/javase/8/docs/api/java/io/PipedInputStream.html) and [PipedOutputStream](https://docs.oracle.com/javase/8/docs/api/java/io/PipedOutputStream.html) for this. Assuming that our callbacks and IO are running on different threads.

**Comment by whiskeysierra** [comment]
http://ostermiller.org/utils/javadoc/CircularByteBuffer.html

**Comment by whiskeysierra** [comment]
```xml
<dependency>
    <groupId>org.ostermiller</groupId>
    <artifactId>utils</artifactId>
    <version>1.07.00</version>
</dependency>
```

**Comment by tkrop** [comment]
Try this one:

https://github.com/RobAustin/low-latency-primitive-concurrent-queues

**Comment by tkrop** [comment]
Okay. I have checked  [PipedInputStream](https://docs.oracle.com/javase/8/docs/api/java/io/PipedInputStream.html) and [PipedOutputStream](https://docs.oracle.com/javase/8/docs/api/java/io/PipedOutputStream.html) again. Your initial Idea was right!!

Even if we have no single producer thread situation it works for us, as the producer thread reference is updated whenever a new bytes are written. If NIO does only use one IO Thread at a time to push data to the pipeline it will work, even if the pushing thread changes in between. If not, we can synchronize on the [PipedOutputStream](https://docs.oracle.com/javase/8/docs/api/java/io/PipedOutputStream.html) to coordinate producer threads - even for security.
