### ISSUE TITLE
Consolidate usage of http mock servers in tests

### ISSUE THREAD

**Issue by fatroom** [zalando/riptide#1392]
## Context
Currently the different tests in the code base use MockRestServiceServer from spring framework as well as RestDriver (same named library). 
RestDriver is based on jetty 9 which is incompatible with the spring framework 6. 
For moving forward we need to avoid direct relation on java.servlet based packages.

## Possible Implementation
Keeping #837 in mind it's better to avoid usage of MockRestServiceServer in the tests, so we can use use MockWebServer from [OkHttp](https://github.com/square/okhttp/tree/master/mockwebserver).
The library is independent from javax.server namespace problems, as well as providing good enough level control. 

Another option would be to wait for wiremock 3 release (beta version of wire mock 3 already available, though not sure if that would be possible without simultaneous migration of the spring framework to version 6 due to JEE api changes)

**Comment by Semernitskaya** [comment]
## Mock servers comparison approach
I've compared suggested implementations. 
   
I've collected main use cases of `RestDriver` in the project tests (e.g. `verify()`, respond with delay, use custom `org.apache.http.client.HttpClient`), wrote a test with main use cases using `RestDriver` - see [HttpMockTestClientDriver](https://github.com/zalando/riptide/pull/1437/files#diff-9d3eb8d0977d210dcee3b726f6148ba0eeedd34ede18662b9679472cfda3fa7c), then I tried to rewrite this test using different mock servers implementations.
   
**Notes:**
1. Test is located in `riptide-failsafe` module as I'm better familiar with it from my previous task and many use cases are based on tests from `riptide-failsafe` (e.g. processing delayed response)
2. After rewriting, every test case can be executed successfully, and the same logic is verified.

## Mock servers comparison results
### Spring MockRestServiceServer
### OkHttp MockWebServer
### WireMock WireMock class

**Comment by Semernitskaya** [comment]
@fatroom I agree, yes sure - I'll continue working on this task. My plan:
- Migrate modules one by one
- Send draft PR when first couple of modules are migrated to make sure that I'm on the right track 
- Delete MockSetup classes (they are used for Spring MockRestServiceServer initialisation)
- Keep Spring MockRestServiceServer in spring related modules (riptide-spring-boot-starter, riptide-spring-boot-autoconfigure)
