### ISSUE TITLE
Remove Completion in favor of CompletableFuture

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#163]
It doesn't provide much value over CompletableFuture, in fact for most use cases you need to transform it anyway, e.g. to use `CompletableFuture.allOf()` etc.

**Comment by whiskeysierra** [comment]
I'll delay this until we've seen some more pain points.

**Comment by lukasniemeier-zalando** [comment]
I wanted to use the static methods of `CompletableFuture` - which I could not do before I found `toCompletableFuture`.

**Comment by whiskeysierra** [comment]
@lukasniemeier-zalando Should we return a `CompletionStage<Void>` or a `CompletableFuture<Void>`? The first one would be an interface but it doesn't offer a way to block (you'd need to call `toCompletableFuture` first). The second one has all of that but also methods like `complete(Void)` or `completeExceptionally(Throwable)` which expose way too much, in my opinion.

Thoughts?
