### ISSUE TITLE
Resolve URIs against Base URL

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#168]
URIs are currently taken as-is, i.e. base URL is not prepended. This leads to weird scenarios where clients want to use URI facilities, e.g. resolve, but still need the base URL.

- [x] add example table to README
- [ ] describe URL transformation
- [ ] release notes describing the breaking change (https://example.org/api + /users is **not** https://example.org/api/users but rather https://example.org/users)

**Comment by lukasniemeier-zalando** [comment]
What happens if you have a base-url configured and the client specifies an absolute URL?

**Comment by whiskeysierra** [comment]
| Base URL                | URI                     | Result                      |
|-------------------------|-------------------------|-----------------------------|
| https://example.com     | /foo                    | https://example.com/foo     |
| https://example.com     | https://example.org/foo | https://example.org/foo     |
| https://example.com/api | /foo                    | https://example.com/foo     |
| https://example.com/api | foo                     | https://example.com/api/foo |

**Comment by lukasniemeier-zalando** [comment]
:+1: put this in the JavaDoc?

**Comment by whiskeysierra** [comment]
@lukasniemeier-zalando I changed the table again, because it had an error (https://example.com/api + foo resolves to https://example.com/foo **not** https://example.com/api/foo).

**Comment by whiskeysierra** [comment]
As a little summary (to be put in the README later): We apply the following operations:

**URI Template** (String)
- parameter expansion (`/{id}`)
- encoding

**URI**
- none, used *as is*

**Both** (after respective transformation)
- resolved against Base URL (if present)
- Query String (merged with existing)
- Normalization
