### ISSUE TITLE
Riptide-Capture README ...

### ISSUE THREAD

**Issue by jbellmann** [zalando/riptide#171]
in the [Example-Code](https://github.com/zalando/riptide/tree/master/riptide-capture#example) is a 'join()' at the end. In the same snippet on [Usage](https://github.com/zalando/riptide/tree/master/riptide-capture#usage) is no 'join()'. Which one is correct? Both?

**Comment by whiskeysierra** [comment]
join blocks, you need this for `Order` since you need the actual response, while `Completion<Order>` represents the compuations, hence you don't need to block.
