### ISSUE TITLE
Provide support for querying configured baseUrl

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/riptide#189]
As a developer
I want to query Rest's `baseUrl` without explicitly providing any path
So that it it possible to do so

Proposal is to add no-argument get, post, put, etc methods which will call preconfigured baseUrl or fail if there is no one configured.

**Comment by whiskeysierra** [comment]
> Proposal is to add no-argument get, post, put, etc methods which will call preconfigured baseUrl or fail if there is no one configured.

Would you still disallow empty strings?

**Comment by AlexanderYastrebov** [comment]
yes, they feel and look ugly

**Comment by AlexanderYastrebov** [comment]
Actually `""` is a valid uriTemplate :)
