### ISSUE TITLE
Document how various URIs / URI Templates work with empty baseUrl

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/riptide#190]
Extend table in README

**Comment by whiskeysierra** [comment]
> Document how various URIs / URI Templates work with empty baseUrl

They just do :stuck_out_tongue_winking_eye:. Riptide will produce the correct result (without a scheme/host/port) but then the actual http layer underneath (e.g. Apache HttpClient) will fail with:

    IllegalArgumentException: URI is not absolute

**Comment by whiskeysierra** [comment]
See https://docs.oracle.com/javase/8/docs/api/java/net/URI.html#toURL--

> This convenience method works as if invoking it were equivalent to evaluating the expression new URL(this.toString()) after first checking that this URI is absolute.

**Comment by whiskeysierra** [comment]
Related to the first part of #191:

> If there is no baseUrl configured, then no URL resolution is ever made and request should provide absolute URL. If request does not provide absolute URL, it should fail.
