### ISSUE TITLE
Introduce baseUrl strict resolution rule support

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/riptide#191]
When `baseUrl` strict resolution rule is enabled:
* If there is no `baseUrl` configured, then no URL resolution is ever made and request should provide absolute URL. If request does not provide absolute URL, it should fail.
* If `baseUrl` is configured, then request path is always appended to `baseUrl` (with leading/trailing slashes between `baseUrl`'s path and request path normalized) so it is impossible to override `baseUrl`'s path or execute a query with absolute URL. If query with absolute URL is made it should fail.

Strict resolution rule could be enabled e.g. via addition of `RestBuilder` method `public RestBuilder baseUrl(@Nullable final String baseUrl, final boolean strict)`.
The rule should be disabled by default for backward compatibility.

**Comment by whiskeysierra** [comment]
I'd separate those two aspects. The first one can be enabled in all cases, already today. The second one is interesting, but I wouldn't call it strict. The RFC is strict, this one is lax.

**Comment by whiskeysierra** [comment]
@AlexanderYastrebov Would you consider that #200 completely implements this feature?

**Comment by AlexanderYastrebov** [comment]
@whiskeysierra Yes, I think so
