### ISSUE TITLE
Resilience: Transient Faults

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#225]
We have have support for transient faults in the form of the [riptide-exceptions](https://github.com/zalando/riptide/tree/master/riptide-exceptions) module. It classifies exceptions into permanent and temporary exceptions.

> A transient fault is a fault that is no longer present if power is disconnected for a short time and then restored; or an insulation fault which only temporarily affects a device's dielectric properties which are restored after a short time.
>
> https://en.wikipedia.org/wiki/Fault_(power_engineering)#Transient_fault

We may consider to:
- [x] rename the module to `riptide-faults` or `riptide-transient-faults`
- [x] rename the exception type to `TransientFault` or `TransientFaultException`
- [x] rename the module to `TransientFaultModule`
- [x] rename `ExceptionClassifier` to `FaultClassifier`
- [x] new banner, e.g. https://pixabay.com/en/electric-light-bulb-wire-rain-2616487/
- [x] include wikipedia quote in Readme

**Comment by lukasniemeier-zalando** [comment]
Also have `FaulClassifier` configurable (globally)
