### ISSUE TITLE
Migrate from Put-it-to-REST

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando/riptide#235]
Add a two liner on how to migrate from Put-it-to-REST to the new starter. Is it just changing the key in my configuration?

- [ ] Change `rest` key to `riptide`
- [ ] Change `connection-timeout` to `connect-timeout`
- [ ] Change `plugins` to:
  - [ ] `preserve-stack-trace`
  - [ ] `detect-transient-faults`
- [ ] No hystrix support, use failsafe, if applicable
- [ ] Bean IDs?
- [ ] Different defaults
  - [ ] Maximum connections per route
- [ ] Bounded queues by default

**Comment by whiskeysierra** [comment]
See https://github.com/zalando-stups/put-it-to-rest#migration
