### ISSUE TITLE
TypedCondition::call should use Optional

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando/riptide#25]
Right now ``TypedCondition::call`` expects a ``EntityConsumer<I>`` when creating a ``Binding`` for type ``I``. I think it would be better if the consumer is of ``EntityConsumer<Optional<I>>``.

Looking at ``HttpMessageConverterExtractor`` there are some cases where the ``entity`` will be ``null`` (e.g. empty response body for a *HEAD* request). Client's should think about such cases when using ``TypedCondition::call``.

**Comment by whiskeysierra** [comment]
Clients that use `HEAD` requests should be aware that they get a null body. There is not better support to retrieve headers:

```java
rest.execute(..).dispatch(status(),
  on(OK).map(headers()).capture(),
  ..
```

`headers()` could alternatively replaced by `HttpMessage::getHeaders`
