### ISSUE TITLE
Configure HTTP Client passed to Tokens library

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#260]
The tokens library allows to configure a custom `HttpProviderFactory`. The current implementation already uses Apache HTTP Client: `ClosableHttpProviderFactory`. But the way it's configured is not really compatible with our configuration. 

The following things might be interesting to utilize:
- retries
- circuit breaker
- certificate pinning

**Comment by lukasniemeier-zalando** [comment]
Or use a full fledged riptide client and replace the Tokens library by riptidified implementation.

**Comment by whiskeysierra** [comment]
In K8s, would we actually still need any HTTP client at all? Aren't we reading tokens directly from the local filesystem?

**Comment by whiskeysierra** [comment]
Fixed in #584
