### ISSUE TITLE
Resilience: Backup Request

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#265]
A new plugin that implement backup requests. Also known as *Fan Out, Quickest Reply*  and *Hedged Requests*.

**Comment by whiskeysierra** [comment]
- https://research.google.com/people/jeff/latency.html
- https://research.google.com/people/jeff/Berkeley-Latency-Mar2012.pdf
- http://www.cs.duke.edu/courses/cps296.4/fall13/838-CloudPapers/dean_longtail.pdf

**Comment by whiskeysierra** [comment]
[Possible Banner](https://pixabay.com/en/pipe-taps-plumbing-water-valve-1821109/)

**Comment by tkrop** [comment]
To be honest, I think this is a very academic and rare use case for Riptide that is not worth implementing unless you really stumble over it - some one requests it.

**Comment by whiskeysierra** [comment]
@tkrop It's in the same way academic as retries are (since backup requests are just early retries). The google slide deck actually pretty neatly shows that in services that fan-out, you'll increase the likelihood of experiencing a long latency-tail by a lot. There is nothing really academic about it, it's simple statistics:

> Server with 1 ms avg. but 1 sec 99%ile latency
–touch 1 of these: 1% of requests take ≥1 sec
–touch 100 of these: 63% of requests take ≥1 sec
