### ISSUE TITLE
Schedulers should do minimal work

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#283]
Follow-up from #279 

1. Executing a request should be as short, i.e. as async, as possible
2. Callbacks should not be executed by the scheduler. That may happen if the scheduler thread completes the future.

**Comment by lukasniemeier-zalando** [comment]
> Callbacks should not be executed by the scheduler. That may happen if the scheduler thread completes the future.

Or hand off execution to a specified thread pool after scheduler is done. spring-boot-starter may configure the `http-xyz` pool of the client.
