### ISSUE TITLE
Change HttpBuilder to a staged builder

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#295]
Request factory is in fact a mandatory dependency, but the API allows to create an `Http` instance without it, but fails at runtime. Changing the API would make this a compile time error.

See https://immutables.github.io/immutable.html#staged-builder. Whether we should use `Immutables` for this, that's up to discussion.

**Comment by lukasniemeier-zalando** [comment]
What about just changing `Http#builder()` to `Http#builder(AsyncClientHttpRequestFactory)`?

**Comment by whiskeysierra** [comment]
Would work as well. But as soon as we have multiple mandatory parameters, then it would get a bit messier.
