### ISSUE TITLE
DefaultFaultClassifier classifies root cause but not throwable itself

### ISSUE THREAD

**Issue by AlexanderYastrebov** [zalando/riptide#310]
From the code it looks like that `DefaultFaultClassifier` classifies root cause but not throwable itself.

**Comment by whiskeysierra** [comment]
That's correct. Do you have a scenario in mind where this doesn't work?

**Comment by AlexanderYastrebov** [comment]
Yes, it basically will not work for exceptions without root cause

**Comment by AlexanderYastrebov** [comment]
~~Yes, it basically will not work for exceptions without root cause~~

It does not support coarse classification - if client want to classify top-level exception without going into details of root cause

**Comment by whiskeysierra** [comment]
> It does not support coarse classification - e.g. if client wants to classify top-level exception without going into details of root cause

Do you have a real-world example?

**Comment by AlexanderYastrebov** [comment]
Consider
```java
        try (Session<?> session = ftp.getSession()) {
           ...
        } catch (final Exception e) {
            final CompletableFuture<Void> future = new CompletableFuture<>();
            future.completeExceptionally(classifier.classify(e));
            return future;
        }
```

and 
```java
public X getSession() {
    try {
    ...
    } catch (Exception e) {
        throw new IllegalStateException("failed to create SFTP Session", e);
    }
}
```

It is impossible to classify all session creation problems as temporary, i.e. impossible to classify `IllegalStateException` with message `"failed to create SFTP Session"` itself, only its root cause.

**Comment by AlexanderYastrebov** [comment]
I think we are actually talking about [`DefaultFaultClassifier` ](https://github.com/zalando/riptide/blob/master/riptide-faults/src/main/java/org/zalando/riptide/faults/DefaultFaultClassifier.java#L17)
which might be extended to classify throwable itself together with its cause chain

**Comment by tkrop** [comment]
The usual problem is, that the outer exceptions are hiding different root causes, some temporary, some final. I cannot see how filtering on behalf of the outer exception is solving a problem.

**Comment by AlexanderYastrebov** [comment]
> The usual problem is, that the outer exceptions are hiding different root causes, some temporary, some final. I cannot see how filtering on behalf of the outer exception is solving a problem.

There is no way to classify all the different causes (assuming they are all temporary) at once by classifying outer exception like in example above.

**Comment by tkrop** [comment]
> There is no way to classify all the different causes (assuming they are all temporary) at once by classifying outer exception like in example above.

Yes, you are right. Unless you do a full code analysis with all potential exceptions, you can never know for sure. Anyhow, it is much worse to classify a none-temporary failure as temporary - which might result in a live-lock - as doing the reverse. This is the reason for catching only the well-known cases by default and handling all unknown temporary failures as durable.

**Comment by AlexanderYastrebov** [comment]
> Yes, you are right. Unless you do a full code analysis with all potential exceptions, you can never know for sure. Anyhow, it is much worse to classify a none-temporary failure as temporary - which might result in a live-lock - as doing the reverse. This is the reason for catching only the well-known cases by default and handling all unknown temporary failures as durable.

I assume user of library knows his usecases and is able to decide on granularity of classification on his own. And if he would like to have classification of outer exception - there is no way to do it right now by default.

**Comment by tkrop** [comment]
Yes, I understand, but there is just no use to this approach, because it eventually will lead to infinite retries - unless you have a limit in the first place, in which case you do not even need classify exceptions at all.

**Comment by whiskeysierra** [comment]
@AlexanderYastrebov Do you still feel like this should get special support? I just want to highlight that someone could implement a custom classifier, so there is enough freedom to implement it like you wanted.
We may want to extend the readme to highlight that the default approach is a *root cause* analysis, i.e. that we exclusively inspect the root cause of exceptions.

**Comment by AlexanderYastrebov** [comment]
The question is what is the best/expected default behavior from client perspective: to test only the root cause or to test causality chain starting with throwable itself.
