### ISSUE TITLE
Compilation issues

### ISSUE THREAD

**Issue by pawang15** [zalando/riptide#337]
Not Sure but am getting compilation issues in lot many classes example BackupRequestPlugin.class like variable scheduler is not initialized.

**Comment by whiskeysierra** [comment]
Can you post some code how you're using it?

**Comment by pawang15** [comment]
I just downloaded the project and imported into my work space

**Comment by whiskeysierra** [comment]
Travis is able to build it, see https://travis-ci.org/zalando/riptide/branches and so can I locally. What version of Maven and Java do you use? Can you post the output of `mvn -version`?

**Comment by pawang15** [comment]
Its JDK 1.8 and maven 2

**Comment by pawang15** [comment]
Even I tried both Release and Master branches but see problem in both.

Am also astonishing how come it has compilation issue. I am suspecting it
should be some dependency issue am getting

**Comment by whiskeysierra** [comment]
Maven 2 is pretty old. I guess it doesn't support Lombok's annotation processor correctly.

**Comment by whiskeysierra** [comment]
I guess you're using eclipse. You should take a look at https://projectlombok.org/setup/eclipse

**Comment by whiskeysierra** [comment]
Maven should work either way though. But you should run a newer version:

```bash
$ mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /home/wschoenborn/Applications/maven
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-109-generic", arch: "amd64", family: "unix"
```

**Comment by pawang15** [comment]
I tried both IntelliJ and eclipse actually

**Comment by whiskeysierra** [comment]
For IntelliJ you should install https://plugins.jetbrains.com/plugin/6317-lombok-plugin

**Comment by pawang15** [comment]
Awesome it work after this plugin :-)

May I know what is the necessity of this ?

**Comment by pawang15** [comment]
Willi - Just curious !!! Does it require JDK 1.9 Mandatory or its still
fine with JDK 1.8 ?

**Comment by whiskeysierra** [comment]
Master still works with Java 1.8

**Comment by pawang15** [comment]
WIlli - My criteria is to support Generic response from any endpoint
payload in structure.

Can you help me which snippet and module help me to do this ?

**Comment by whiskeysierra** [comment]
Reading it into a `JsonNode` should be the most generic way.

**Comment by pawang15** [comment]
Ya that's the only option I can see thanks for response

**Comment by pawang15** [comment]
Hey Willi-

I just want to use  riptide <https://github.com/zalando/riptide>/
*riptide-httpclient*/ in my project with resttemplate flavor . What all
steps I need to follow ?

Listed below are the steps based on documentation

1 .) Import dependency

<dependency>
    <groupId>org.zalando</groupId>
    <artifactId>riptide-httpclient</artifactId>
    <version>${riptide.version}</version>
</dependency>


2. ) private final CloseableHttpClient client =
HttpClientBuilder.create().build();
    private final AsyncListenableTaskExecutor executor = new
ConcurrentTaskExecutor();
    private final RestAsyncClientHttpRequestFactory factory = new
RestAsyncClientHttpRequestFactory(client, executor);

3. )  final RestTemplate template = new RestTemplate(factory);
        template.setMessageConverters(singletonList(createJsonConverter()));


That's it or have to do extra stuff too.

Thanks
Pawan

**Comment by whiskeysierra** [comment]
I'd strongly suggest to use the riptide-spring-boot-starter. Alternatively:

https://github.com/zalando/riptide/blob/04584d5a956cb8c676e5317bc2148abcfdcb08ce/riptide-spring-boot-starter/src/test/java/org/zalando/riptide/spring/ManualConfiguration.java#L144

**Comment by pawang15** [comment]
How can I disable Oauth from   riptide-spring-boot-starter.

**Comment by pawang15** [comment]
Willi -

I included these dependencies in my POM attached in this email but still
its looking for so many jar's which are missing.

Am I doing anything wrong here ??
