### ISSUE TITLE
Immutable Requester

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#338]
Instead of modifying headers/query parameters and returning `this`, we may return a modified copy of the requester. That allows client to prepare requesters.

**Comment by AlexanderYastrebov** [comment]
This will break some clients - returning `this` is a fluent API but there is no way to ensure that client uses API in fluent way.

Consider this example where client does not use fluent API
```java
    Requester r = ...
    r.queryParam("x", "y");
    r.contentType(JSON);

    return r;
```
Returning copy will break such clients since they expect `r` to be mutable.

**Comment by whiskeysierra** [comment]
> This will break some clients

I know, that's why I targeted this for 3.0.

**Comment by AlexanderYastrebov** [comment]
> I know, that's why I targeted this for 3.0.

It does not matter, since there is no way to enforce client to use API in fluent way.
It is not clear to me what would be the value of this change? Could the same result be achieved differently?

**Comment by whiskeysierra** [comment]
> It does not matter, since there is no way to enforce client to use API in fluent way.

Since solves ~90% of the problem: https://immutables.github.io/immutable.html#staged-builder

> It is not clear to me what would be the value of this change?

My goal is to prepare requesters:

```java
private final Requester accounts = http.get("/accounts");

accounts.query("owner", me)
    .dispatch(..);
```

For this to be more useful it should allow to set path variables as well, e.g. `/accounts/{account}`.

**Comment by AlexanderYastrebov** [comment]
> My goal is to prepare requesters:

Would then implementing `clone` be an alternative?

**Comment by AlexanderYastrebov** [comment]
My point is that fluent API could be used in two ways and how it would be used is our of library control. 
Returning `this` works both ways and thus is safe while returning copy provides an opportunity for non obvious bugs and thus is unsafe.

**Comment by whiskeysierra** [comment]
> Would then implementing clone be an alternative?

This is based on the idea of being *mutable by default*. I'm strongly in favor of immutable by default, unless there is a reason not to.

> returning copy provides an opportunity for non obvious bugs and thus is unsafe

What about this bug? Is it less dangerous?

```java
private final Requester getAccounts = http.get("/accounts");

public List<Account> getAccountsByOwner(final String name) {
    return getAccounts.query("owner", name).dispatch(..).join();
}
```

**Comment by tkrop** [comment]
@whiskeysierra immutability is a nice thing, but I agree with @AlexanderYastrebov: a builder pattern is expected to mutate until it is frozen by building an entity/request. Immutability in my opinion should be applied to entities.

May the whole discussion is a result of the name `Requester` which is not transporting the builder semantic?

**Comment by whiskeysierra** [comment]
> a builder pattern is expected to mutate until it is frozen by building an entity/request

Why would it? A builder is meant to be used multiple times, not just once.

**Comment by tkrop** [comment]
Because it is a builder. If it is a factory, it is meant to be used multiple times.

**Comment by whiskeysierra** [comment]
1. I'd argue that builders are allowed to be mutable, but there is no requirement to do so.
2. Requester never stated or specified that it is a builder or which semantics it follows.

We advocate the fluent API style which will continue to work. On top of that I'm planning to allow to share  them so similar requests can share their setup without having to worry about concurrent modifications.

**Comment by tkrop** [comment]
I can see this. I'm just arguing to stick to known patterns (and name classes accordingly) to give clients the least possible surprise. That the name Requester does not state which pattern it is implementing is in my opinion part of the problem.

In addition, I think an Immutable builder-based creation pattern is neither helpful to prevent bugs not necessary.

**Comment by whiskeysierra** [comment]
> That the name Requester does not state which pattern it is implementing is in my opinion part of the problem.

Exactly, so nobody can rely that it's a builder and that builders always have to be mutable for some reason.

> I think an Immutable builder-based creation pattern is neither helpful to prevent bugs not necessary.

Immutability is always one of the best solutions to prevent concurrency bugs. There is no easy fix when it comes to mutable instances.
