### ISSUE TITLE
Reconsider exception handling concept

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#35]
Right now the exception handling is kind of shady:

- `any*().call(..)` handles the *no match case* (which is fine)
- it also catches and swallows any `RestClientException` and `HttpMessageNotReadableException`
- the general idea should be: pass through everything *as-is* from custom callbacks/mappers as well as from the underlying RestTemplate
- the only case I can think of right now that justifies a custom exception is *no match* without an *any* condition

**Comment by lukasniemeier** [comment]
Where are ``RestClientException``s swallowed? The only [place they are caught](https://github.com/zalando/riptide/blob/4baa0dae2697a447debd80a722c12b8a76dc2891/src/main/java/org/zalando/riptide/TypedCondition.java#L50) right now, I ask myself whether they are ever thrown at this call. This is actually the same place ``IOException`` originate from, which are [later wrapped](https://github.com/zalando/riptide/blob/4baa0dae2697a447debd80a722c12b8a76dc2891/src/main/java/org/zalando/riptide/Dispatcher.java#L55) into a ``RestClientException``.

**Comment by whiskeysierra** [comment]
> whether they are ever thrown at this call

E.g. "no suitable HttpMessageConverter found for response type" (not sure if this is the one from us though)

> This is actually the same place IOException originate from, which are later wrapped into a RestClientException.

I'd also like to get rid of this nesting
