### ISSUE TITLE
Spring Boot 1.5.x Ease of Integration

### ISSUE THREAD

**Issue by lukasniemeier-zalando** [zalando/riptide#401]
Since [2.8.0](https://github.com/zalando/riptide/tree/2.8.0) riptide-metrics requires `io.micrometer` instead of `io.dropwizard.metrics`, which makes it harder to integrate with Spring Boot 1.5.x,

## Description

After upgrading Riptide to 2.8.0 our `ApplicationContext` failed to started, due to a missing bean of type `io.micrometer.core.instrument.MeterRegistry`. Adding [*micrometer-spring-legacy*](https://micrometer.io/docs/ref/spring/1.5) to our classpath fixed the Spring context issue, but metrics were not exposed via actuator endpoint `/metrics` anymore (see https://github.com/zalando/riptide/tree/2.8.0/riptide-metrics#usage).

By default *micrometer-spring-legacy* uses the in-memory `SimpleMeterRegistry`. This registry does not expose their metrics to the actuator endpoint. Only when adapting the `DropwizardMeterRegistry` in our service allows us to use riptide-metrics and have metrics exposed via `/metrics`. This combination requires some boilerplate code:

```java
@Bean
public MeterRegistry meterRegistry(final MetricRegistry metricRegistry, final Clock clock) {
    final DropwizardMeterRegistry registry = new DropwizardMeterRegistry(new DropwizardConfig() {
        @Override
        public String prefix() {
            return "foobar";
        }

        @Override
        public String get(final String key) {
            return null;
        }
    }, metricRegistry, HierarchicalNameMapper.DEFAULT, clock) {
        @Override
        protected Double nullGaugeValue() {
            return null;
        }
    };
    registry.config().namingConvention(NamingConvention.identity);
    return registry;
}
```

```yaml
management.metrics.binders:
  files.enabled: false
  jvm.enabled: false
  processor.enabled: false
  uptime.enabled: false
```

## Possible Fix

We should at least document the required dependency to *micrometer-spring-legacy* for Spring Boot 1.5.x. 

Additionally it would be nice to have a better integration with `io.micrometer` for Spring Boot 1.5.x:

* no need for having both Dropwizard *and* `io.micrometer`
* still having metrics exposed via a management endpoint

## Steps to Reproduce

1. Spring Boot 1.5.x Application
2. Add riptide-metrics 2.8.0
3. See context failing

## Your Environment
* Version used: Spring Boot 1.5.13 with Riptide 2.8.0

**Comment by whiskeysierra** [comment]
> We should at least document the required dependency to micrometer-spring-legacy for Spring Boot 1.5.x.

See #404.

> Additionally it would be nice to have a better integration with io.micrometer for Spring Boot 1.5.x:
> 
> no need for having both Dropwizard and io.micrometer

I'd say it's acceptable for 1.5.x users. 2.x no longer needs Dropwizard.

> still having metrics exposed via a management endpoint

I added a link to this issue from the README.

**Comment by whiskeysierra** [comment]
I also added a link to this issue from the release notes for 2.8.0.
