### ISSUE TITLE
Should retries be restricted to idempotent requests?

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#440]
## Detailed Description

The failsafe plugin issues retries based on the exception but completely ignores the request method, i.e. even `POST` requests are retried right now.

## Context

The backup request already filters for *safe* request methods. Maybe it's safer to do something similar for retries? 

## Possible Implementation

No concrete idea yet, but there is a chance of sharing some code between backup request and failsafe plugin, since all safe methods are inherently idempotent.

## Your Environment

* Version used: 2.9.0-RC.3

**Comment by whiskeysierra** [comment]
The `X-HTTP-Method-Override` header allows clients to *mark* requests as safe (assuming the override is a safe method). I don't know of something like that for idempotent requests.

**Comment by whiskeysierra** [comment]
The presence of a `Idempotency-Key` header would be one idea.

**Comment by whiskeysierra** [comment]
[AWS](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/Run_Instance_Idempotency.html#client-tokens) uses `ClientToken` as a query parameter for this.

**Comment by whiskeysierra** [comment]
https://news.ycombinator.com/item?id=13707681

**Comment by whiskeysierra** [comment]
Safe methods https://tools.ietf.org/html/rfc7231#section-4.2.1
Idempotent methods https://tools.ietf.org/html/rfc7231#section-4.2.2

**Comment by whiskeysierra** [comment]
>    Idempotent methods are distinguished because the request can be
   repeated automatically if a communication failure occurs before the
   client is able to read the server's response.  For example, if a
   client sends a PUT request and the underlying connection is closed
   before any response is received, then the client can establish a new
   connection and retry the idempotent request.  It knows that repeating
   the request will have the same intended effect, even if the original
   request succeeded, though the response might differ.

**Comment by whiskeysierra** [comment]
Are conditional requests actually idempotent by definition? 
[RFC 7232](https://tools.ietf.org/html/rfc7232) doesn't mention *idempontency* at all. From a logical perspective, I'd say yes. The side effect on the server happens at most once. Which should make it safe for retries.
This [discussion] claims otherwise at some place, but it's a discussion after all.

**Comment by tkrop** [comment]
My 2 cent: *idempotency* of requests is very service implementation specific aspect. If API producers stick to the rules for `GET` and `PUT` this is fine, but they can although decide to do so for `POST` and `PATCH`.

Anyhow, isn't `failsafe` only used for cases, where it is clear that the request has not been processed by the service? I.e. if the connection failed, the request could not be transmitted, or the service responded with 503 (or may be 429)? As I see it, on any other error (response) `failsafe` should inform the requester immediately.

Based on this assumptions I do not see any reason to check more for *idempotency* here at all.

@whiskeysierra do I miss something?

**Comment by whiskeysierra** [comment]
> Anyhow, isn't failsafe only used for cases, where it is clear that the request has not been processed by the service?

No. Right now we also consider socket timeouts as transient faults and retry them. Same for `NoHttpResponseException` (apache http client) which is thrown when the server closes the connection while we wait for a response. Especially for those cases I'd like to restrict retries to requests that are idempotent.

**Comment by tkrop** [comment]
Okay, I see - thanks for explaining (and I can see the history why it is so ;)).

Anyhow, in my opinion it is not predictable whether *read errors* are *transient errors*. E.g. a request that is triggering a process that is consistently creating a read timeout, because the result processing takes to long is not *transient* unless you increase the *read timeout*.

Thus, I think it is not wise to cover this cases within the default `riptide-failsafe` plugin configuration on http client level. Still, I can see the advantage of using a single mechanism for retries, but I can although see the risk of doing so.

Independent of implementing this via `riptide-failsafe`, in my opinion marking *read errors* as *transient* should not be a default option, but should be selected very explicit based on each request invocation.

**Comment by tkrop** [comment]
> We have a maximum number of retries for that one in particular.

The limitation is a necessary starting point, but effectively already to late. Any retry in such a situation will quickly results in an exponential progressing overload situation, when normal requests start to fail too. While this may go away after a short while it makes the system unnecessary instable.

**Comment by whiskeysierra** [comment]
That's what we have circuit breakers for, haven't we?

**Comment by tkrop** [comment]
Yes, but I'm not sure whether it is a good strategy to drive a service into overload and than use a circuit breaker to be all able to get it out of this. The best system is the one that never needs to circuit break.

**Comment by whiskeysierra** [comment]
But how do you know your server is overloaded from the client's perspective? A circuit breaker is just a failsafe in order to not run into that situation where you never stop issuing requests. In a perfect world we wouldn't need it, true. But distributed systems are never perfect.

**Comment by tkrop** [comment]
You can't unless the server responds with 429. Still you can optimize `riptide-failsafe` to not fall into this trap. As I suggested:

1. Remove all `read errors` from the default retry behavior of `transient errors`.
2. Add a feature that explicitly allows clients to enable retry on `read errors` in addition to `transient errors` - only on request basis.

**Comment by whiskeysierra** [comment]
@tkrop See #450 which outlines a proposal for 3.x tackling this in a more structured way.
