### ISSUE TITLE
SOAP support

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#510]
## Detailed Description

Add a new `riptide-soap` module that provides reusable type tokens/converters/routes/... to deal with SOAP requests, incl. marshalling/unmarshalling, handling of envelopes and faults.

## Context

We sometimes have to integrate against legacy SOAP web services and can't use Riptide to it's fullest potential. Right now we configure a client (using the spring boot starter) and use it to construct a customized WebServiceTemplate.

## Possible Implementation

- [x] `riptide-soap` module
- [ ] Possible [Banner](https://pixabay.com/photos/faucet-soap-hand-washing-fountain-1581573/)

**Comment by whiskeysierra** [comment]
https://github.com/OpenFeign/feign#soap

**Comment by jmatusewicz** [comment]
🎆 ❤️
