### ISSUE TITLE
Access to both headers and deserialized body from the response

### ISSUE THREAD

**Issue by olayinkasf** [zalando/riptide#514]
## Detailed Description

I can't have access to the headers unless I bind to a consumer of the `ClientHttpResponse`, it would be nice to be able to consume a `ResponseEntity<T>` where `T` is the expected  type of the body.

## Context

Accessing headers together with deserialized ResponseBody

## Your Environment

* Version used:
* Link to your project:

**Comment by whiskeysierra** [comment]
I guess you found it already, but for the record, in case someone else is looking for it:

https://github.com/zalando/riptide/blob/0b8928a07b212b732590f4b9aaccdc8056ab8d20/riptide-core/src/test/java/org/zalando/riptide/CallTest.java#L80-L83
