### ISSUE TITLE
Release connection instead of abort

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#519]
## Detailed Description

Within the `RestAsyncClientHttpResponse` we abort connections when closing the response instead of releasing it back to the pool.

## Context

Releasing it back to the pool would in theory allow for a connection to be reused.

## Possible Implementation

https://github.com/zalando/riptide/blob/0b8928a07b212b732590f4b9aaccdc8056ab8d20/riptide-httpclient/src/main/java/org/zalando/riptide/httpclient/RestAsyncClientHttpResponse.java#L43

Call [`releaseConnection`](https://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/conn/ConnectionReleaseTrigger.html#releaseConnection()) instead.

## Your Environment

* Version used: 2.10.1

**Comment by tkrop** [comment]
I know this code :smiley_cat:.

I fuzzily remember that `close()` didn't work, because it was silently ignored somewhere up in the call chain. However, this might have change since I analyzed it 2.5 years ago - anyhow, better look out before changing this.

Wondering, whether something similar may be reason for #520.

**Comment by jhorstmann** [comment]
If I remember correctly, `abortConnection` had to be used to close a streaming (nakadi) connection, as the normal `close` operation would try to consume the endless stream of remaining data.

**Comment by whiskeysierra** [comment]
I think we could fix it by doing the following:

1. If riptide consumes the response body before returning anything then we can safely *release* the connection. This includes unmarshalling into a Pojo.
2. If riptide doesn't consume the response body but rather return something to the caller that has to be closed then we should *abort* the connection to be on the safe side since we don't know whether the caller consumed everything, forgot to consume or maybe even can't consume it at all (e.g. streams). This includes returning a `ClientHttpResponse` directly or a `Stream`.
