### ISSUE TITLE
Should we resolve relative Location/Content-Location headers automatically?

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#52]

**Comment by lukasniemeier** [comment]
When accessed via [Actions](https://github.com/zalando/riptide/blob/239ffc4a016dde1059f6e21e54614a40625bd249/src/main/java/org/zalando/riptide/Actions.java#L46)?

**Comment by jhorstmann** [comment]
[RFC 2616][1] said

> The field value consists of a single absolute URI.

But that definition got updated in [RFC 7231][2], which now also allows a relative url

> The field value consists of a single URI-reference.  When it has the form of a relative reference, the final value is computed by resolving it against the effective request URI.

So it makes sense to do this automatically in `Actions`, if a user wants the original value it's still possible to access the response header directly.

 [1]: https://tools.ietf.org/html/rfc2616#section-14.30
 [2]: https://tools.ietf.org/html/rfc7231#section-7.1.2

**Comment by whiskeysierra** [comment]
> When accessed via Actions?

We don't have access to the request url at that point. I was thinking about [Rest.execute](https://github.com/zalando/riptide/blob/239ffc4a016dde1059f6e21e54614a40625bd249/src/main/java/org/zalando/riptide/Rest.java#L57):

```java
    private <T> Dispatcher execute(final HttpMethod method, final URI url, final HttpEntity<T> entity) {
        final Callback<T> callback = new Callback<>(template.getMessageConverters(), entity);
        final ClientHttpResponse response = execute(method, url, callback);
        return new Dispatcher(template, response);
    }
```

I'd wrap the ClientHttpResponse to modify the headers transparently. That wouldn't allow this anymore though:

> if a user wants the original value it's still possible to access the response header directly.

**Comment by lukasniemeier-zalando** [comment]
IMO original header values should be still be accessible. If this is a common pattern what about some syntactic sugar for the sugar-function `location()` :wink: ? Something like 
```
capture(location().andThen(resolve(uri)))
```

**Comment by tkrop** [comment]
I agree with @lukasniemeier. Moreover, keeping the response as is, is in my opinion absolutely important to prevent clients of being surprised. How about adding a more straight forward method like `capture(resolvedLocation(uri))` or even better `capture(resolve(location(), uri))` to `Actions` that automatically resolves the absolute location based on a given base URI.

**Comment by whiskeysierra** [comment]
All proposals would only work for a single captured URL. I had a specific use case in mind: As a client I want to check whether Location and Content-Location are the same, i.e. *Is the response body the current representation of the resource?*

**Comment by lukasniemeier-zalando** [comment]
Ergo allowing a multi-`Capture`?

**Comment by whiskeysierra** [comment]
I was thinking more towards capturing the whole Response (with normalized URL-style headers):

```java
ClientHttpResponse response = rest.execute(..).dispatch(series(),
        on(SUCCESSFUL).capture(normalized(uri)),
        ..);

if (response.getHeaders().getLocation().equals(response.getHeaders().getContentLocation())) {
    return rest.read(response, Body.class);
} else {
    return rest.execute(GET, response.getHeaders().getLocation()).dispatch(series(),
            on(SUCCESSFUL, Body.class).capture(),
            ..).to(Body.class);
}
```

I'd like to make this paradigm easier.

**Comment by whiskeysierra** [comment]
I played around a little and came up with this:

```java
final Success success = unit.execute(POST, url)
        .dispatch(series(),
                on(SUCCESSFUL).map(normalize(url).andThen(response -> {
                    final HttpHeaders headers = response.getHeaders();
                    final URI location = headers.getLocation();

                    return Optional.ofNullable(headers.getFirst(CONTENT_LOCATION))
                            .map(URI::create)
                            .filter(location::equals)
                            .map($ -> unit.process(response).to(Success.class))
                            .orElseGet(() ->
                                    unit.execute(GET, location).dispatch(series(),
                                            on(SUCCESSFUL, Success.class).capture())
                                            .to(Success.class));
                })).capture(),
                on(CLIENT_ERROR, Exception.class).call(propagate()))
        .to(Success.class);
```

- the location/content-location header handling is ugly
- it's something that is not easy to express declaratively
- as soon as you allow to handle responses imperatively, you'll need something like `Rest.process(ClientHttpResponse)`, so you can transform a raw response to a typed return value
