### ISSUE TITLE
Add token info uri to riptide properties

### ISSUE THREAD

**Issue by ssalome** [zalando/riptide#549]
When using riptide, we get a logging warning from org.zalando.stups.tokens.TokenVerifyRunner with "No AccessToken-Verification enabled because no 'tokenInfoUri' was configured"

## Detailed Description
I propose that `tokenInfoUrl` is added to `RiptideProperties.GlobalOAuth` as an optional property.

## Context

We try to have only warnings and errors in our logs when it is something that we should act on it, so we would like to remove this warning.

## Possible Implementation

[PR548](https://github.com/zalando/riptide/pull/548)

**Comment by whiskeysierra** [comment]
I'd prefer to take this discussion over to https://github.com/zalando/tokens and either reduce the log level or get rid of the feature completely.

**Comment by ssalome** [comment]
Thank you for your quick reply! I'll create an issue there ;)
