### ISSUE TITLE
Allow call() with a parameterless "consumer" (e.g.. Runnable)

### ISSUE THREAD

**Issue by ePaul** [zalando/riptide#56]
There are some cases where the conditions of the dispatch function are already everything which is interesting (i.e. neither response body nor any remaining header information matter). (An example is the `200` response from Nakadi's "submit events" operation.)

But currently I still need to pass to `.call()` a consumer of either some class mapped from the response, or even the HttpClientResponse.

I propose to add a `call` method in UntypedCondition which accepts a `Runnable` (or a throwing version thereof), simply discarding the ClientHttpResponse and calling the runnable.

For now I'm using this `wrap` function as a workaround:

```java
    private static ThrowingConsumer<ClientHttpResponse, ?> wrap(Runnable runnable) {
        return response -> runnable.run();
    }
```

**Comment by whiskeysierra** [comment]
This addition would be especially interesting in regards of support for AsyncRestTemplate, where any code that needs to run after a response needs to be supplied as some kind of callback. (Compared to be just placed after the call to `rest.execute(..)`.

**Comment by tkrop** [comment]
@whiskeysierra @ePaul is there semantic difference of this suggestion to `rest.execute(GET, url).dispatch(status(),on(UNAUTHORIZED).capture())`?

**Comment by ePaul** [comment]
@tkrop I'm not sure I understand your question.

The point of `call(...)` is to specify code to execute, with `capture()` you say "store something for later retrieval". (Though I'm not sure what is actually captured in your example.)

Currently I can say 

```java
rest.execute(GET, url).dispatch(status(),
          on(OK).call(response -> callback.successfullyPublished()));
```
But this response is not actually used in the callback (it's a void method without parameters), thus I would like to be able to say
```java
rest.execute(GET, url).dispatch(status(),
          on(OK).call(callback::successfullyPublished));
```
directly. This is the difference between a `Consumer<ClientHttpResponse>` and a `Runnable`.

**Comment by whiskeysierra** [comment]
@ePaul Are you willing to do a pull-request?

**Comment by ePaul** [comment]
I'll have a try, can't promise it will work.

**Comment by whiskeysierra** [comment]
I can't think of a reason why it shouldn't.

**Comment by ePaul** [comment]
First thing going wrong is that my home computer has no Java 8, and the Ubuntu is old enough there isn't even a package to install it. So, it might take a while until I set up everything. (Also, 4 GB seems to not be enough to run Eclipse and Opera with several tabs open at the same time.)
