### ISSUE TITLE
Rename MetricsPlugin to MicrometerPlugin

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#700]
## Context

- consistency with other plugins:
  - `FailsafePlugin` (not `CircuitBreakerPlugin`, `RetryPlugin` or `ResiliencePlugin`)
  - `LogbookPlugin` (not `LoggingPlugin`)
  - `OpenTracingPlugin` (not `TracingPlugin`)

**Comment by fatroom** [comment]
Do you want to rename riptide-metrics subproject as well? Or is it just for the plugin class?

**Comment by whiskeysierra** [comment]
Didn't think of it, but you're right. Module needs to be renamed as well.
