### ISSUE TITLE
Modularize Auto Configuration?

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#723]
## Detailed Description

Alternative to #620 

Would it be beneficial to modularize the auto configuration and delegate responsibility to each module that wants to participate?

## Possible Implementation

- [ ] Define service provider interface
- [ ] Use service loader to supply implementations from each module

## Your Environment

* Version used:
* Link to your project:

**Comment by fatroom** [comment]
Can you check the issue number that you're referencing here? 627 is about bumping guava

**Comment by fatroom** [comment]
Regarding general idea: spring boot utilises the single auto configuration module to wire up dependencies if they're available in class path. I would prefer to stay with the approach utilised by boot, and familiar to the most of the people who was looking inside of spring.

**Comment by whiskeysierra** [comment]
> Can you check the issue number that you're referencing here?

Fixed. It should've been #620

**Comment by whiskeysierra** [comment]
> I would prefer to stay with the approach utilised by boot, and familiar to the most of the people who was looking inside of spring.

I don't want to change anything from the perspective of the user. There would still be a `riptide-spring-boot-autoconfigure` module with a `RiptideAutoConfiguration` class in it. What I'm trying to tackle is the underlying implementation because right now If we change something in any of the modules we almost always have to go into the autoconfigure module and apply changes there to allow some feature being using in a spring boot application with ease. It violates the open/closed principle since I now have to touch that module every time. Would be nice to be able to extend its behavior without modifying.

**Comment by fatroom** [comment]
hm. even if your concern about OCP will be addressed by splitting configuration, this seems to me an overkill, since 
1) it will bring spring dependency in every module (think about part that will read config, either one more common module targeted to spring)
2) I don't see actually how that solve #620 ?
