### ISSUE TITLE
riptide-micrometer module not exists

### ISSUE THREAD

**Issue by jbellmann** [zalando/riptide#732]
The [Migration-Guide mentions a package name change](https://github.com/zalando/riptide/blob/master/MIGRATION.md#micrometer) from `riptide-metrics` to `riptide-micrometer` but the [renamed module does not exist](https://search.maven.org/search?q=riptide-micrometer) (while `riptide-metrics` can be [found versioned for latest RC](https://search.maven.org/artifact/org.zalando/riptide-metrics/3.0.0-RC.2/jar)).

## Possible Fix
- create `riptide-micrometer` and release it to maven-central
or
- stay with `riptide-metrics` and remove the micrometer section in the [migration guide](https://github.com/zalando/riptide/blob/master/MIGRATION.md#micrometer)

**Comment by whiskeysierra** [comment]
> * create `riptide-micrometer` and release it to maven-central

I'm currently trying to release 3.0.0-RC.3 but I'm hitting some timeout issues with Nexus...

**Comment by whiskeysierra** [comment]
https://github.com/zalando/riptide/releases/tag/3.0.0-RC.3
