### ISSUE TITLE
riptide-spring-boot-starter reference incorrect about default retry configuration

### ISSUE THREAD

**Issue by jbellmann** [zalando/riptide#751]
While using riptides retry configuration we faced some minor issues with the [reference documentation](https://github.com/zalando/riptide/tree/master/riptide-spring-boot-starter#reference) about some defaults.

## Description
Reference documentation stated that the default `max-duration` (TimeSpan) is not set by default. But [it seems to be a TimeSpan of 5 seconds](https://github.com/zalando/riptide/blob/master/riptide-spring-boot-autoconfigure/src/main/java/org/zalando/riptide/autoconfigure/RiptideProperties.java#L81).

Reference documentation stated that the default `max-retries` is not set by default. But [it seems to be 2](https://github.com/jhalterman/failsafe/blob/master/src/main/java/net/jodah/failsafe/RetryPolicy.java#L75).

## Expected Behavior
We expected to have no `max-duration` set to `null/none`.  We expected delays were resolved dynamically by response headers returned by services like `X-RateLimit-Reset`. But most of the time returned values are greater than 5 seconds.

We expected to have `max-retries` not set to behave like infinite number of retries.

## Actual Behavior
`max-duration` (summarized amount of time for all retries) kicks in and makes dynamic resolving delay useless.

`max-retries`: Retries were canceled after second 429 response from service even if service answered again with 429 response.

## Possible Fix
`max-duration`: initialise with `null`

`max-retries`: update reference documentation.

**Comment by whiskeysierra** [comment]
> `max-duration`: initialise with `null`

That was actually intentional but I missed to update the docs. The reason being that there should be a default for safety reasons because otherwise a fault service configuration will make your client go into an endless loop. Regardless of whether you have dynamic delays, you almost always should have a maximum.
