### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#76]
- [x] add title, e.g. *Riptide: Client-side Response Routing*
- [x] add descriptions to selectors
- [x] add origin/reason for existence
- [x] document that the underlying RestTemplate shouldn't be changed afterwards
- [x] define Route and RoutingTree
- [x] Visualize routing tree
- [x] How to systematically produce a routing tree
- [x] How to programmatically modify the routing tree

**Comment by lukasniemeier-zalando** [comment]
- [ ] remove all references to `RestTemplate`
- [ ] fix formatting in [stream doc](https://github.com/zalando/riptide/blob/release/2.0.0/riptide-stream/README.md)
- [ ] clarify last sentence of [stream doc](https://github.com/zalando/riptide/blob/release/2.0.0/riptide-stream/README.md)
