### ISSUE TITLE
The bean 'taskScheduler', defined in null, could not be registered.

### ISSUE THREAD

**Issue by RohanNg** [zalando/riptide#770]
## Description

I tried running latest riptide version `3.0.0-RC.4`  and springboot version `2.1.8.RELEASE`. However, the Springboot application could not start. It failed with error:

> The bean 'taskScheduler', defined in null, could not be registered. A bean with that name has already been defined in class path resource [org/zalando/riptide/autoconfigure/RiptideAutoConfiguration$SchedulingAutoConfiguration.class] and overriding is disabled.

Possible place of error cause:
https://github.com/zalando/riptide/blob/589544b3863b0b280682875a08c8d5d08e857242/riptide-spring-boot-autoconfigure/src/main/java/org/zalando/riptide/autoconfigure/RiptideAutoConfiguration.java#L35

For now I need to enable Bean overriding as a work around. `allow-bean-definition-overriding: true`.

**Comment by whiskeysierra** [comment]
I believe the `AutoConfigureAfter` annotations need to be also on the inner classes directly.

**Comment by whiskeysierra** [comment]
Can you paste the whole stacktrace?
