### ISSUE TITLE
Unclear documentation/configuration around AuthorizationProvider in starter

### ISSUE THREAD

**Issue by jrehwaldt** [zalando/riptide#780]
Spring Boot Starter of Riptide 3.0.0-RC.4

The documentation indicates that a bean of type `AuthorizationProvider` can be wired to override the default oauth variant. Unfortunately, this only works when setting `riptide.clients.<ID>.oauth.enabled: true`. The setup of the `AuthorizationPlugin` is conditional behind this property in `DefaultRiptideRegistrar.registerAuthorizationPlugin`.

Setting `oauth.enabled: true` in order to use a non-oauth implementation is misleading and not really straight-forward. I am not sure how it is best solved.

## Possible Implementation
* Rename property to just `auth`; maybe introduce `auth.provider: oauth` or just `auth.oauth: ...` to conditionally setup Zalando's defaults
* Always wire `AuthorizationPlugin` when `AuthorizationProvider` is found; disadvantage is it cannot be disabled in tests
* allow wiring an `AuthorizationPlugin` instead of `AuthorizationProvider` (isn't currently picked up)
* leave as is and require the user to use a the custom plugin feature when using a custom `AuthorizationProvider`

**Comment by whiskeysierra** [comment]
>     * allow wiring an `AuthorizationPlugin` instead of `AuthorizationProvider` (isn't currently picked up)

That would solve the issue, would it?

**Comment by whiskeysierra** [comment]
>     * Rename property to just `auth`; maybe introduce `auth.provider: oauth`

I'm probably going with this.

**Comment by whiskeysierra** [comment]
After discussing this with @lukasniemeier-zalando we decided to add `auth` as an alias for `oauth`. In order not to break anyone we would still support `oauth` for the time being but log a warning if used.
