### ISSUE TITLE
CircuitBreakers are not picked up by failsafe-actuator

### ISSUE THREAD

**Issue by fatroom** [zalando/riptide#846]
## Description
Not sure if the issue of riptide or actuator actually
Got riptide-failsafe plugin and failsafe-actuator in my project, failsafe-actuator register it self first and doesn't see any circuit breakers due to the fact that they're registered programmatically afterwards. 

## Expected Behavior
I see the state of riptide circuit breakers on actuator endpoint.

## Actual Behavior
actuator endpoint is empty

## Possible Fix
Change the order of the registration

## Your Environment
* Version used: 3.0.RC-8
* Link to your project:

**Comment by whiskeysierra** [comment]
Looks like this is not enough:

https://github.com/zalando/riptide/blob/5e99633d0fbf7f40d23da37c9b28baa63aa92d6b/riptide-spring-boot-autoconfigure/src/main/java/org/zalando/riptide/autoconfigure/RiptideAutoConfiguration.java#L21-L24

Probably because we only register the post processor there and the autoconfigure after doesn't take beans into account that are created from within.

**Comment by whiskeysierra** [comment]
Any idea how to fix that?

**Comment by whiskeysierra** [comment]
Maybe we could change `CircuitBreakersEndpointAutoConfiguration` to not inject a map, but rather lookup all circuit breakers whenever they are needed? That way it would gain the ability to react to late changes of the application context.

**Comment by fatroom** [comment]
That was my first idea to check this settings.
No clear vision at the moment, but I see few ways:
- one of the possible fixes would be try to enforce riptide to be registered on top of everything
- force failsafe-actuator to be registered the last (then this issue will move to riptide actuator, or at least document the solution here if it's possible to do via regular application config)
- lazy init of failsafe actuator/discover circuit breakers on first call

**Comment by whiskeysierra** [comment]
> one of the possible fixes would be try to enforce riptide to be registered on top of everything

That doesn't really work because I want the auto-configuration feeling in Riptide, i.e. all beans that Riptide registers should step back if a user defines some themselves.

**Comment by jrehwaldt** [comment]
I just wanted to open an issue for this. Isn't the problem that the `CircuitBreaker` is not actually accessible from the bean context, but rather wrapped inside a `[Default]RequestPolicy`?

**Comment by whiskeysierra** [comment]
Yes, you're right. We need to expose the circuit breaker as a proper bean.

**Comment by fatroom** [comment]
As well introduced by #784
