### ISSUE TITLE
Support reuse of routers for routing trees.

### ISSUE THREAD

**Issue by tkrop** [zalando/riptide#85]
Currently, users users have to create the routing tree for each Rest instance. As far as I can see the routing tree for many request is pretty the same (pretty likely thread safe) and can be often declared static in advance of the request and reused on different occasions.

To allow declaration of independent routing trees, on solution would be support the stand alone creation and reuse of routers for routing trees. An example usage would look as follows:

    private static final Router<MediaType> CONTENT_ROUTER = create(contentType(),
            on(TEXT_PLAIN).capture(String.class),
            anyContentType().call(MyTest::failContent));

    private static final Router<HttpStatus> STATUS_ROUTER = create(status(),
            on(OK).dispatch(CONTENT_ROUTER),
            on(BAD_GATEWAY).call(MyTest::badGateway),
            anyStatus().call(MyTest::failStatus));

...

        Rest rest = Rest.create(new RestTemplate());
        rest.execute(GET, URI.create("http://my.uri/api"))
                .dispatch(STATUS_ROUTER)
                .as(String.class);

**Comment by whiskeysierra** [comment]
Fixed with #86
