### ISSUE TITLE
BOM pulls in Spring BOM version

### ISSUE THREAD

**Issue by jrehwaldt** [zalando/riptide#866]
I am not sure if the following is intended or not:

`riptide-bom` inherits from `riptide-parent`, which pins a whole lot of additional dependencies other than riptide. Among these are the BOM for spring-boot-dependencies and spring-framework.

When using Spring's dependency management plugin and gradle to import riptide's bom it'll override the project's Spring Boot version (and in turn all other dependencies defined by Spring):

```
buildscript {
    dependencies {
        classpath "org.springframework.boot:spring-boot-gradle-plugin:2.2.2.RELEASE"
    }
}

...

dependencyManagement {
    imports {
        mavenBom "org.zalando:riptide-bom:3.0.0-RC.9"
    }
}

...
```

Now `riptide-bom:3.0.0-RC.9` pulls in dependencies declared in `riptide-parent`, which in turn defines spring-boot-dependencies at version 2.2.1.RELEASE. This will then be the version used for the whole project. The same applies for all dependencies defined in the parent pom's `<dependencyManagement>` section.

## Expected Behavior
Riptide-bom defines only riptide dependencies and nothing else.

## Actual Behavior
Riptide-bom defines dependency versions other than riptide. Among these is `spring-boot-dependencies` BOM. This messes the full dependency tree up and is rather difficult to mitigate.

## Possible Fix
1. Do not inherit from `riptide-parent` in `riptide-bom`.
2. Split `riptide-parent` into two poms: one that defines metadata, e.g. `riptide-build`, and another that inherits from it and defines project-wide versions. Then inherit `riptide-bom` from `riptide-build`.
3. Do not add `<dependencyManagement>` section in `riptide-parent`. (Somewhat defeats the purpose of it than :D)

(The same issue applies to logbook-bom. I'm not going to create a ticket there for now.)

Does that make sense? Maybe I am doing something stupid here?!

**Comment by whiskeysierra** [comment]
>     2\. Split `riptide-parent` into two poms: one that defines metadata, e.g. `riptide-build`, and another that inherits from it and defines project-wide versions. Then inherit `riptide-bom` from `riptide-build`.

I looked at https://github.com/kemitix/kemitix-maven-tiles recently with something like that in mind. I also wanted to take this one into consideration: https://itnext.io/writing-a-full-featured-maven-pom-f5b874eef312#3672

Are you interested in proposing a PR?

**Comment by jrehwaldt** [comment]
I am not exactly sure I understand your idea. Specifically, I am not sure which would be the tiles you envision?

My thought was that the following would be sufficient:
1. `riptide-build` with everything but `<dependencyManagement>`
2. `riptide-parent` inherited from `-build` and added `<dependencyManagement>`
3. `riptide-bom` inherits only from `-build`, whereas all the others inherit from `-parent`

**Comment by fatroom** [comment]
This caused by gradle way of working with maven bom.
 Maven gives the preference what ever version you got declared in your pom, but gradle takes versions from boms as preferred.
In this case actually you just need to add `id 'io.spring.dependency-management' version '1.0.8.RELEASE'` to your plugins section. It will take care about proper spring version that was declared in your build.gradle instead of default gradle behaviour.

**Comment by fatroom** [comment]
But generally saying I would vote for the simplistic structure proposed by @jrehwaldt instead of bringing additional maven plugins in to the play.

**Comment by fatroom** [comment]
hm, seems that something fishy in your setup.
```
# cat build.gralde
plugins {
	id 'org.springframework.boot' version '2.1.11.RELEASE'
	id 'io.spring.dependency-management' version '1.0.8.RELEASE'
	id 'java'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '1.8'

repositories {
	mavenCentral()
}



dependencies {
        implementation(platform("org.zalando:riptide-bom:3.0.0-RC.9"))
        implementation 'org.zalando:riptide-core'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
./gradlew dependencies
+--- org.zalando:riptide-bom:3.0.0-RC.9
|    +--- org.springframework.boot:spring-boot-starter-test:2.2.1.RELEASE -> 2.1.11.RELEASE (c)
...
```

without dependency management plugin:

```
# cat build.gradle
plugins {
	id 'org.springframework.boot' version '2.1.11.RELEASE'
	id 'java'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '1.8'

repositories {
	mavenCentral()
}



dependencies {
        implementation(platform("org.zalando:riptide-bom:3.0.0-RC.9"))
        implementation 'org.zalando:riptide-core'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
# ./gradlew dependencies
+--- org.zalando:riptide-bom:3.0.0-RC.9
|    +--- org.springframework.boot:spring-boot-starter-test:2.2.1.RELEASE (c)
...
```

**Comment by whiskeysierra** [comment]
> I am not exactly sure I understand your idea. Specifically, I am not sure which would be the tiles you envision?

You could put the build part into a tile.

**Comment by jrehwaldt** [comment]
@fatroom Declaring BOMs using the "new" Gradle 5 way indeed works:
```
plugins {
    id 'org.springframework.boot' version '2.1.11.RELEASE'
    id 'io.spring.dependency-management' version '1.0.8.RELEASE'
    id 'java'
}

repositories { mavenCentral() }

dependencies {
    implementation(platform("org.zalando:riptide-bom:3.0.0-RC.9"))
    implementation 'org.zalando:riptide-core'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
```

When using the pre-Gardle 5 setup provided by Spring's own gradle-dependency-plugin the versions are messed up when importing a BOM such as riptide's:
```
plugins {
    id 'org.springframework.boot' version '2.1.11.RELEASE'
    id 'io.spring.dependency-management' version '1.0.8.RELEASE'
    id 'java'
}

repositories { mavenCentral() }

dependencyManagement {
    imports {
        mavenBom "org.zalando:riptide-bom:3.0.0-RC.9"
    }
}

dependencies {
    implementation 'org.zalando:riptide-core'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
```

-> 

```
+--- org.zalando:riptide-core -> 3.0.0-RC.9
...
+--- org.springframework.boot:spring-boot-starter-web -> 2.2.1.RELEASE
```

Good to know there is a better and working approach using the idiomatic Gradle 5 setup. Thank you for this suggestion.

Nonetheless, I'd argue the external dependencies shouldn't be contained in the BOM in the first place.

@whiskeysierra With the build part being in the tile you want to drop the parent altogether from all modules?

**Comment by whiskeysierra** [comment]
I haven't used tiles at all, so take this with a grain of salt. My current idea would be to drop the parent completely and only *pick and choose* those tiles that you actually need in individual poms. The problem that I already see is that a) IDE support would be bad and b) even worse dependabot won't be able to bump versions anymore.

So extracting a second parent that can be used directly if needed sounds like the best approach right now.

**Comment by jrehwaldt** [comment]
@fatroom There are additional implications of the inheritance from `riptide-parent`: It defines certain exclusions, which propagate into projects relying on `riptide-bom`:

```
<dependencyManagement>
            ...
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter</artifactId>
                <version>${spring-boot.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>ch.qos.logback</groupId>
                        <artifactId>logback-classic</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.springframework</groupId>
                        <artifactId>spring-jcl</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
</dependencyManagement>
```

This effectively excludes logback from being pulled in transitively when depending on `org.springframework.boot:spring-boot-starter` for anyone using the BOM, for example.

**Comment by fatroom** [comment]
I want to try the structure similar to spring-boot maven usage:
```
- root
  - module 1
  - parent
  - bom
 ```
will make few checks, and create PR if that's working as expected

**Comment by whiskeysierra** [comment]
`root`: everything except dependency management
`parent`: `root` + dependency management?

**Comment by fatroom** [comment]
@whiskeysierra correct, root everything beside dependency management, parent  inherits from root and adds dependency management.
bom inherits from root, others from parent

**Comment by whiskeysierra** [comment]
Do you want to do it?

**Comment by fatroom** [comment]
yep, will take care
