### ISSUE TITLE
Bundle static factory methods in Riptide class

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#89]

**Comment by ePaul** [comment]
May I ask "Why"?

(Or worded differently: Please put some info about your motivation into the issues.)

**Comment by whiskeysierra** [comment]
Right now static factories are spread across multiple different classes, e.g. Actions, Conditions and Selectors. Having a single class would make it easier for developers to find the right method, since they'd know where to look.

This was actually brought up by @tkrop Maybe I'm missing some other aspect.

**Comment by whiskeysierra** [comment]
@ePaul @AlexanderYastrebov @jhorstmann @lukasniemeier-zalando @tkrop Can we have a vote on this? I don't have a strong opinion. Just leave a reaction to the top comment.

**Comment by whiskeysierra** [comment]
That includes :-1:

**Comment by AlexanderYastrebov** [comment]
Can you provide an example?

**Comment by whiskeysierra** [comment]
Right now we have static factory methods spread across the following classes:
- Actions
- Conditions
- Selectors

Those are being used by pretty much everybody that uses Riptide. The idea was to bundle them all in the same class so users only need to statically import one of them or in other words to have a single place to look for.

**Comment by AlexanderYastrebov** [comment]
But not as a fluent API that is instantly discoverable?

**Comment by ePaul** [comment]
There is no emoticon for "I don't care", so no such vote for me. (I just commented because I wanted the reasoning in the issue, as a general principle.)

**Comment by jhorstmann** [comment]
I haven't looked at all the static methods we have, but I don't think bundling them all on one class will make the api easier discoverable.

**Comment by whiskeysierra** [comment]
> But not as a fluent API that is instantly discoverable?

No.

**Comment by lukasniemeier-zalando** [comment]
I agree with @jhorstmann, but I'd see a fluent API (like @AlexanderYastrebov is hinting for) as the best.

**Comment by whiskeysierra** [comment]
A completely fluent API makes it harder to extract and restructure a routing tree.

**Comment by whiskeysierra** [comment]
I'm closing this now, as the votes were not in favor of it.

**Comment by tkrop** [comment]
I'm not absolutely convinced about that idea myself, but the problem is, that the riptide API is not really fluent. The fluency in my opinion is broken where the user is required to create a second level fluent object like a Binding.

In this case the entry point is hard to find, as it is not in Binding but in Condition. In addition the package has many classes that sidetrack the users focus from the entry points. To improve this, the idea was to make the entry points better visible, e.g. by bundling them through a Riptide class.
