### ISSUE TITLE
Unify syntax

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/riptide#99]
```java
rest.xyz(GET, "/products/{id}", id)
        .accept(MediaTypes.PRODUCT, MediaTypes.PROBLEM)
        .header("Foo", "bar")
        .dispatch(series(),
            on(SUCCESSFUL).capture(Product.class),
            anySeries().call(fail()));
```

```java
rest.xyz(GET, "/products/{id}", id)
        .dispatch(series(),
            on(SUCCESSFUL).capture(Product.class),
            anySeries().call(fail()));
```

- [x] find good name for initial method

**Comment by lukasniemeier-zalando** [comment]
If Riptide wants to honor its roots it would be `exchange/execute`

**Comment by whiskeysierra** [comment]
But those methods actually do the request already. If we make headers and body optional it would need to go in the dispatch function.

**Comment by AlexanderYastrebov** [comment]
Dont you want to got with five like: `rest.get` `rest.post` and so on?

**Comment by whiskeysierra** [comment]
Also an idea. I like the enum as a first parameter because it looks like the actual HTTP request line:

```http
HTTP/1.1 GET /products/123
```

```java
http.send(GET, "/products/123")
```

Actually, while looking at, your example would also be very similar:

```java
http.get("/products/123")
```

(Both have actually the same Levenshtein Distance :wink:)

**Comment by whiskeysierra** [comment]
I think I'll go with both, `send` (or `execute`) as the generic one and one per method.

**Comment by ePaul** [comment]
> Also an idea. I like the enum as a first parameter because it looks like the actual HTTP request line:

>      HTTP/1.1 GET /products/123

But the actual request line is something like this:

    GET /products/123 HTTP/1.1

Sorry, I just had to nitpick here.

**Comment by whiskeysierra** [comment]
> But the actual request line is something like this:
> 
> GET /products/123 HTTP/1.1
> Sorry, I just had to nitpick here.

Good catch!

**Comment by AlexanderYastrebov** [comment]
I dont like verb (other than HTTP verbs) as method name because it is hard to link it to REST resource domain. You are not sending or executing or queriyng ot what ever. You exactly do GET POST PUT on resource.

**Comment by whiskeysierra** [comment]
Ok, so just the following?
- `delete`
- `get`
- `head`
- `options`
- `patch`
- `post`
- `put`
- `trace`

**Comment by ePaul** [comment]
The problem with that approach is that HTTP is extensible with additional methods – which then would not be supported by your library. I guess this is the reason for a generic method in addition to the HTTP-verb-named ones in RestTemplate and other HTTP client libraries.

See the [HTTP Method registry](http://www.iana.org/assignments/http-methods/http-methods.xhtml).

**Comment by AlexanderYastrebov** [comment]
@ePaul noone restricts us from adding general one like `execute`, but we can cover 99.99 by using HTTP verbs

**Comment by whiskeysierra** [comment]
> The problem with that approach is that HTTP is extensible with additional methods – which then would not be supported by your library. I guess this is the reason for a generic method in addition to the HTTP-verb-named ones in RestTemplate and other HTTP client libraries.

Not really, since Spring's [`HttpStatus`](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/http/HttpMethod.html) is already an enum that doesn't implement any interface.

**Comment by whiskeysierra** [comment]
See #105
